import mongoose from "mongoose";

const manufacturingOrderSchema = new mongoose.Schema({
  moNumber: { type: String, unique: true, required: true },
  productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true },
  productName: { type: String, required: true },
  bomId: { type: mongoose.Schema.Types.ObjectId, ref: "BillOfMaterials" },
  salesOrderId: { type: mongoose.Schema.Types.ObjectId, ref: "SalesOrder" },
  quantity: { type: Number, required: true },
  producedQuantity: { type: Number, default: 0 },
  scrapQuantity: { type: Number, default: 0 },
  scheduledStart: { type: String, required: true },
  scheduledEnd: { type: String, required: true },
  actualStart: String,
  actualEnd: String,
  status: { type: String, default: "draft" }, // draft, confirmed, in_progress, completed, cancelled
  warehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse", required: true },
  notes: String,
  autoGenerated: Boolean,
}, { timestamps: true });

manufacturingOrderSchema.index({ productId: 1 });
manufacturingOrderSchema.index({ status: 1 });
manufacturingOrderSchema.index({ salesOrderId: 1 });

export default mongoose.model("ManufacturingOrder", manufacturingOrderSchema);
