import mongoose from "mongoose";

const rfqSchema = new mongoose.Schema({
  rfqNumber: { type: String, unique: true, required: true },
  vendorId: { type: mongoose.Schema.Types.ObjectId, ref: "Vendor", required: true },
  date: { type: String, required: true },
  dueDate: String,
  items: [{
    productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
    productName: String,
    sku: String,
    quantity: Number,
    unitPrice: Number,
  }],
  status: { type: String, default: "draft" }, // draft, sent, received, converted, cancelled
  notes: String,
  autoGenerated: Boolean,
}, { timestamps: true });

rfqSchema.index({ vendorId: 1 });
rfqSchema.index({ status: 1 });

export default mongoose.model("RFQ", rfqSchema);
